max_steps = 200
seq_len = 4096

[deployment]
num_train_gpus = 2
num_infer_gpus = 6

[model]
name = "Qwen/Qwen3-4B-Instruct-2507"

[monitors.wandb]
project = "wiki-search"
name = "wiki-search"

[trainer.optim]
lr = 1e-5
weight_decay = 0.0

[trainer.model.lora]
rank = 8
dropout = 0.0
target_modules = [
    "q_proj",
    "k_proj",
    "v_proj",
    "o_proj",
    "gate_proj",
    "up_proj",
    "down_proj"
]

[orchestrator]
batch_size = 512

[orchestrator.train]
group_size = 16

[orchestrator.concurrency]
initial_inflight = 1024

[orchestrator.model.lora]

[orchestrator.train.sampling]
max_completion_tokens = 512

[[orchestrator.train.source]]
name = "wiki-search"
env.taskset.id = "wiki-search"
env.agent.harness.id = "null"
env.agent.runtime.type = "subprocess"

[ckpt] # Checkpoint at the end of training

[inference.vllm]
tool_call_parser = "hermes"
